### ISSUE TITLE
Telegram 'Bot' not returning weather information....can't figure out what's going on. Please help!

### ISSUE THREAD

**Issue by sedusa** [rvanmil/WeatherDemoBot#1]
Hi René thanks for the excellent blog post! 

I decided to try out the example you provided and was able to setup everything (well at least I think I did) as you instructed but then when I finally tried sending the ```/weather Amsterdam``` command from the Telegram client nothing seemed to happen.  

![No response](http://res.cloudinary.com/drsedusa/image/upload/v1437342325/nothing_lnbptd.png)

My webhook is setup up properly and I didn't run into any problem configuring my Ubuntu server on Digital Ocean.  Is this possible that it could be an issue with the site certificates? A [recent post](http://www.cubewebsites.com/blog/guides/fix-telegram-webhooks-not-working/ "FIX: Telegram Webhooks Not Working") I came across mentions that one solution to solving this issue with the telegram webhooks is to create a chained certificate and update the nginx config file.   Have you run into a similar problem lately? If this does turn out to be an issue with certificates what do you suggest I do?

Any help would be much appreciated as I seem to have hit a wall trying to figure this out.

Thanks.

**Comment by sedusa** [comment]
@rvanmil I think I may have figured out what the problem is.  Just re-read the **'setWebhook'** section of the [Telegram Bot API documentation](https://core.telegram.org/bots/api#getupdates) - #2 'We currently do not support self-signed certificates'.  
![setWebhook Notes](http://res.cloudinary.com/drsedusa/image/upload/v1437352190/note_bhkjct.png)

Going to get a certificate from [sslmate](http://sslmate.com) and see if this solves the problem (fingers crossed).

**Comment by rvanmil** [comment]
Hi Samuel, thanks, I'm glad my blog post was helpful! :)

Looks like you figured it out already, indeed you'll need a valid ssl certificate otherwise the Telegram Bot server won't send updates to your webhook.
An alternative would be to use the `getUpdates` api, which requires you to implement a long polling mechanism on your own server.
